### PR TITLE
Adapted to automatically find enclosure

### PR DESCRIPTION
**Pull request by kroy-the-rabbit**
I adapted the code to automatically search for the enclosure, as my enclosure device would change on reboot.  

Tied to the device either being on /dev/sg or /dev/ses

### CODE REVIEW

**Comment by AndrewX192** [comment]
Nice! I had an item on my backlog to add this myself, but I was using lsscsi... which hasn't always found a /dev/ node for the enclosure despite listing it.

I'll happily merge this in if you take the words "this fork" out of the README. Feel free to add a CONTRIBUTORS file or the the like with your name if you should desire.

Thanks again!

**Comment by kroy-the-rabbit** [comment]
Done.  

This script has been VERY useful to me, so I just wanted to give back anything I could.  No need to add me to any special contributor list.

Thanks again

**Comment by willglynn** [comment]
Erm… I have two SA120s connected to a single host, so with this change, I can only control one of them at random.

**Comment by kroy-the-rabbit** [comment]
@willglynn Definitely correct.  I even have two enclosures but only running one right now, so that's an oversight for sure.  

I started a new pull request to address this.  Simple fix that will at least allow you to set the fan speed on both enclosures.

**Pull request merged**
